<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_instagram_gallery"
 *
 * Auto generated by Extension Builder 2017-03-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] Plugin for Instagram',
    'description' => 'Plugin to display gallery, feeds and phototile with clean, customizable and responsive feeds from multiple Instagram accounts.',
    'category' => 'plugin',
    'author' => 'Sanjay Chauhan [NITSAN Technologies]',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '6.0.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
